name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            anujdube/github-actions-learn:latest
            anujdube/github-actions-learn:${{ github.sha }}

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull anujdube/github-actions-learn:${{ github.sha }}
            docker stop learn-backend || true
            docker rm learn-backend || true
            docker run -d --name learn-backend -p 80:4040 anujdube/github-actions-learn:${{ github.sha }}
