name: Terraform AWS EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    if: contains(github.event.head_commit.message, '[terraform]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Get and set EC2 Public IP
        id: set_ec2_public_ip
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw public_ip)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_ENV
          echo "::set-output name=ec2_public_ip::${EC2_PUBLIC_IP}"

      - name: Update GitHub Secret
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"value": "'"$EC2_PUBLIC_IP"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/actions/secrets/EC2_PUBLIC_IP"
